version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      fontawesome:
        patterns:
          - "@fortawesome/*"
      eslint:
        patterns:
          - "eslint"
          - "typescript-eslint"
          - "@eslint/*"
          - "eslint-*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
