name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: 'lint-test::ubuntu-latest::node-latest'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install Node latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint:check
      - name: Run test
        run: yarn test

  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    name: 'build::${{ matrix.os }}::node-${{ matrix.node-version }}'

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [20.x]
        include:
          - os: ubuntu-latest
            node-version: latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build project
        run: yarn build
