# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: 'lint::ubuntu-latest::node-latest'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run linter (check only)
        run: yarn lint:check
  
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    name: 'build-test::${{ matrix.os }}::node-${{ matrix.node-version }}'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x]
        include:
          - os: ubuntu-latest
            node-version: 22.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use CMD if running on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo "Using Windows CMD"
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Run test suite
        run: yarn test
